version: "3.7"
services:
  backend:
    image: quay.io/keycloak/keycloak:latest
    container_name: "backend"
    ports:
      - 8080:8080
      - 9990:9990
    command: start-dev
    env_file:
      - stickee.env
    volumes:
      - ./backend:/opt/keycloak

  cloudflare:
    build:
      context: .docker
      dockerfile: cloudflare.Dockerfile
    container_name: "cloudflare"
    volumes:
      - ./web:/root/.cloudflared
      - ./web:/etc/cloudflared
    ports:
      - 80:80
      - 443:443
    command: tunnel run
