version: "3.7"
services:
  backend:
    image: quay.io/keycloak/keycloak:latest
    container_name: "backend"
    ports:
      - 8080:8080
      - 9990:9990
    command: start-dev
    env_file:
      - stickee.env
    volumes:
      - ./backend:/opt/keycloak
