version: "3.7"
services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: "cloudflare"
    volumes: [./cloudflare/stage:/home/nonroot/.cloudflared]
    command: tunnel run

  backend:
    image: quay.io/keycloak/keycloak:latest
    container_name: "backend"
    ports:
      - 8080:8080
      - 9990:9990
    command: start-dev
    env_file: [account.env]
    volumes: [./backend:/opt/keycloak]
