version: "3.7"
services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: "cloudflare"
    volumes: [./settings/prod/cloudflare:/home/nonroot/.cloudflared]
    command: tunnel run

  auth: # keycloak
    image: quay.io/keycloak/keycloak:latest
    container_name: "account_auth"
    command: start-dev
    volumes:
      - ./auth/merge.sh:/opt/keycloak/merge.sh
      - ./auth/themes:/opt/keycloak/themes
    env_file: [./settings/prod/auth.env]

  api: # hasura
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: "account_api"
    volumes: [./api:/hasura]
    env_file: [./settings/prod/api.env]

  front: # nextjs
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: account_front
    command: sh -c "npm install && npm run build && npm run start"
    volumes: [.:/repo]
    env_file: [./settings/prod/front.env]
