version: "3.7"
services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: "cloudflare"
    volumes: [./cloudflare/stage:/home/nonroot/.cloudflared]
    command: tunnel run

  auth: # keycloak
    image: quay.io/keycloak/keycloak:latest
    container_name: "account_auth"
    command: start-dev
    env_file: [account.env]
    volumes: [./backend:/opt/keycloak]

  api: # hasura
    build:
      context: .docker
      dockerfile: api.Dockerfile
    container_name: "account_api"
    volumes: [./api:/hasura]
    env_file: [account.env]
