version: '3.7'
services:

  db:
    image: mysql:8.0
    container_name: 'ST-DB'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  api:
    image: quay.io/keycloak/keycloak:latest
    container_name: 'ST-API2'
    ports:
      - 8080:8080
      - 9990:9990
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: password
    volumes:
      - ./api:/opt/keycloak
    depends_on:
      - db
