version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  backend:
    image: quay.io/keycloak/keycloak:latest
    container_name: "backend"
    ports:
      - 8080:8080
      - 9990:9990
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    volumes:
      - ./backend/themes:/opt/keycloak/themes
    depends_on:
      - db
