"""relation

Revision ID: 3563bb4f4449
Revises: 4690805fa0a3
Create Date: 2022-02-13 00:24:51.329585+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3563bb4f4449'
down_revision = '4690805fa0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
