"""edit relation

Revision ID: 842b6e482ce4
Revises: 93a5aa163cfa
Create Date: 2022-02-27 18:34:01.794457+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842b6e482ce4'
down_revision = '93a5aa163cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
