"""relation

Revision ID: becffe72640e
Revises: 3563bb4f4449
Create Date: 2022-02-13 00:41:50.027020+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becffe72640e'
down_revision = '3563bb4f4449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
