"""edit model

Revision ID: a7e920252163
Revises: 8a2b30c4ff73
Create Date: 2022-02-11 23:59:43.722694+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e920252163'
down_revision = '8a2b30c4ff73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
