"""default add

Revision ID: 93a5aa163cfa
Revises: 100558759588
Create Date: 2022-02-12 22:28:32.401597+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a5aa163cfa'
down_revision = '100558759588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
