ALTER INDEX "UK_J3RWUVD56ONTGSUHOGM184WW2-2" RENAME TO "UK_J3RWUVD56ONTGSUHOGM184WW2_2";
ALTER INDEX "CONSTRAINT_17-2" RENAME TO "CONSTRAINT_17_2";
ALTER TABLE ONLY public.user_group_membership
  ADD CONSTRAINT user_group_membership_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.keycloak_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;